baseURL: "http://example.org/"
languageCode: en-us
title: "Le Bar à Théâtre"
theme: PaperMod
defaultContentLanguage: fr

menu:
  main:
    - identifier: a-propos
      name: A propos
      url: /a-propos/
      weight: 10

    - identifier: bio
      name: Bio
      url: /bio/
      weight: 10

    - identifier: prestations
      name: Prestations
      url: /prestations/
      weight: 10

params:
  defaultTheme: light
  disableThemeToggle: true
  ShowShareButtons: false
  hideMeta: true

  # Table des matières
  ShowToc: true
  TocOpen: true

  profileMode:
    enabled: true
    title: "<Title>" # optional default will be site title
    subtitle: "This is subtitle"
    imageUrl: "<image link>" # optional
    imageTitle: "<title of image as alt>" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Archive
        url: "/archive"
      - name: Github
        url: "https://github.com/"

    socialIcons: # optional
      - name: "facebook"
        url: "https://www.facebook.com"
      - name: "instagram"
        url: "<link2>"

  # homeInfoParams:
  #   Title: Le bar à théâtre, qu’est-ce que c’est ?
  #   Content: >
  #     Eh bien c’est moi, Daphnée Barat, comédienne, improvisatrice depuis 2009 et intervenante en théâtre et en improvisation théâtrale depuis 2012. Le bar à théâtre, c’est l’envie de diffuser la pratique du théâtre et de l’impro en amateur à des publics de tous niveaux et de tous horizons. La pratique théâtrale est une discipline qui se pratique à tout âge. Que l’on ait 5 ans ou 90 ans, il est toujours intéressant d’apprendre à vivre ensemble, de reconnaître et de partager ses émotions ou encore de développer son langage et sa créativité. 

  #     J’interviens en Île-de-France et les ateliers peuvent se dérouler en entreprise ; en milieu scolaire, hospitalier, associatif ; maisons de retraites, IME, foyers ainsi que pour des groupes de théâtre ou d'improvisation amateurs ou professionnels, à la recherche d’un intervenant.

  #     Pour pousser les portes d’un atelier, il faut juste avoir en tête quelques mots clés :
  #     - Envie ● Venir avec de la motivation, de l’énergie et de la volonté
  #     - Bienveillance ● Évaluer sans se dévaloriser ou dévaloriser les autres, ne jamais se moquer
  #     - Plaisir ● S’amuser, jouer le jeu et oser se lancer
  #     - Partage ● Jouer collectif ! Accepter de vivre et de construire une histoire et/ou un projet ensemble

  # socialIcons:
  #   - name: <platform>
  #     url: <link>
  #   - name: <platform 2>
  #     url: <link2>