baseURL: "https://lebaratheatre.com"
languageCode: fr
title: "Le Bar à Théâtre"
theme: PaperMod
defaultContentLanguage: fr

menu:
  main:
    - identifier: a-propos
      name: À propos
      url: /a-propos/
      weight: 1

    - identifier: prestations
      name: Prestations
      url: /prestations/
      weight: 2

    - identifier: bio
      name: Bio
      url: /bio/
      weight: 3

    - identifier: contact
      name: Contact
      url: /contact/
      weight: 4

params:
  defaultTheme: light
  disableThemeToggle: true
  ShowShareButtons: false
  hideMeta: true

  # Table des matières
  ShowToc: true
  TocOpen: true

  profileMode:
    enabled: true
    title: "<Title>" # optional default will be site title
    # subtitle: "This is subtitle"
    imageUrl: "images/baratheatre_logo_v3.png" # optional
    imageTitle: "<title of image as alt>" # optional
    imageWidth: 300 # custom size
    imageHeight: auto # custom size

  # socialIcons:
  #   - name: "email"
  #     url: "mailto:lebaratheatre@gmail.com"
  #   - name: "phone"
  #     url: "tel:+33682497609"
  #   - name: "facebook"
  #     url: ""
  #   - name: "instagram"
  #     url: ""